name: C++ Workflow
run-name: ${{github.actor}} ran workflow
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Setup MySQL
        run: |
          sudo apt update
          sudo apt install mysql-server
          sudo systemctl start mysql.service
          sudo mysql
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
          ALTER USER 'dbuser'@'localhost' IDENTIFIED WITH mysql_native_password BY '123';
          GRANT ALL ON *.* TO 'dbuser'@'localhost';
          SELECT user,host, authentication_string FROM mysql.user;
          exit
      - name: Setup Database
        run: |
          sudo mysql -u root -p
          123
          source matchmaking_api_db_sql.sql
          quit
      - name: Install C++ Connector to MySQL
        run: sudo apt install libmysqlcppconn-dev
      - name: Install Boost for Crow
        run: sudo apt-get install libboost-all-dev
      - name: Install Git
        run: sudo apt-get install git
      - name: Install JSONCPP
        run: sudo apt-get install libjsoncpp-dev
      - name: Build Project
        run: bazel build //main:main
      - name: Test Project
        run: bazel test --test_output=all //testing:test
      
      
